version = 1

[approve]
auto_approve_usernames = ["dependabot", "github-actions"]

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" or "github-actions" that are "major", "minor" or "patch" version upgrades
usernames = ["dependabot", "github-actions"]
versions = ["major", "minor", "patch"]
